apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-grafana
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.5.12
    helm:
      valueFiles:
        - values/grafana-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
