apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kps
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/aegonish/monitoring.git
    targetRevision: main
    path: helm/kube-prometheus-stack
    helm:
      valueFiles:
        - ../../values/kps-values.yaml
  destination:
    namespace: monitoring-kube-prometheus-stack
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
