apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-root
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/aegonish/monitoring.git
    targetRevision: main
    path: monitoring-k8s/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
