apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kps
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.3.0
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/aegonish/monitoring/main/monitoring-k8s/gitops/values/kps-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
