apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-grafana
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/aegonish/monitoring.git
    targetRevision: main
    path: helm/grafana
    helm:
      valueFiles:
        - ../../values/grafana-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
