apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-tempo
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: 1.7.1   # optional but recommended
    helm:
      valueFiles:
        - monitoring-k8s/gitops/values/tempo-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
